device: 'cuda'
dataset_path: 'data'

dataset: 'cifar10'
num_classes: 
input_height: 
input_width:
input_channel:

unlearning_epochs: 20
frequency_save: 0
batch_size: 128
num_workers: 4
unlearning_lr: 0.01
lr_scheduler: MultiStepLR
steplr_gamma: 0.1
steplr_milestones: [10, 20]
clean_threshold: 0.2

pin_memory: True
prefetch: False
client_optimizer: sgd
sgd_momentum: 0.9
wd: 0.0005

poison_rate: 0.1
target_type: 'all2one'
target_label: 0
trigger_type: 'squareTrigger' 

model: 'preactresnet18'
random_seed: 0
index: 

amp: True 
ratio: 0.01 # Defense 
non_blocking: True

init: True
relearn_epochs: 20
relearn_lr: 0.005 # CIFAR10
relearn_alpha: 0.7 # CIFAR10
# relearn_lr: 0.001 # GTSRB, CIFAR100
# relearn_alpha: 0.001 # GTSRB, CIFAR100
linear_name: "linear"